# Nixpacks Configuration for Railway Backend Deployment

[variables]
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "postgresql"]
workingDirectory = "backend"

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"