# Nixpacks Configuration for Railway Deployment
# LP Assistant Healthcare Platform

[variables]
NODE_VERSION = "18"
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["nodejs", "python311", "postgresql"]

[phases.install]
cmds = [
  "cd frontend && npm ci --only=production",
  "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "cd backend && python -c 'print(\"Backend ready for production\")'"
]

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"

[staticAssets]
"frontend/build" = "/"