services:
  - type: web
    name: deadpool-backend
    env: python
    region: oregon
    runtime: python-3.11
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    buildFilter:
      paths:
        - backend/**
      ignoredPaths:
        - frontend/**
        - node_modules/**
        - "**/Dockerfile*"
        - "**/.dockerignore"
        - "**/docker-compose*"
    plan: free
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://lp-assistant-healthcare.vercel.app,http://localhost:3000
      - key: DATABASE_URL
        fromDatabase:
          name: deadpool-db
          property: connectionString
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: MONGODB_URL
        value: mongodb://localhost:27017
      - key: MONGODB_DB_NAME
        value: lp_assistant_mongo
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: API_V1_STR
        value: /api/v1
      - key: PROJECT_NAME
        value: LP Assistant Healthcare Platform
    healthCheckPath: /health

databases:
  - name: deadpool-db
    databaseName: deadpool
    user: deadpool_user
    region: oregon