name: Deploy to Render

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
      - '.github/workflows/render-deploy.yml'
      - 'render.yaml'

env:
  PYTHON_VERSION: '3.11'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run basic tests
      working-directory: ./backend
      run: |
        python -c "import main; print('Backend imports successfully')"
    
    - name: Trigger Render Deploy
      run: |
        curl -X POST "https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_DEPLOY_HOOK }}"
    
    - name: Wait for deployment
      run: sleep 120
    
    - name: Health check
      run: |
        for i in {1..10}; do
          if curl -f "${{ secrets.BACKEND_URL }}/health"; then
            echo "✅ Backend is healthy!"
            exit 0
          fi
          echo "Attempt $i failed, retrying in 30s..."
          sleep 30
        done
        echo "❌ Health check failed"
        exit 1
    
    - name: Deployment success
      if: success()
      run: |
        echo "🚀 Backend deployed successfully to Render!"
        echo "URL: ${{ secrets.BACKEND_URL }}"