name: Deploy Frontend to Vercel

on:
  push:
    branches: [ main, master ]
    paths:
      - 'frontend/**'
      - '.github/workflows/vercel-deploy.yml'
      - 'vercel.json'

env:
  NODE_VERSION: '18'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Build frontend
      working-directory: ./frontend
      run: CI=false npm run build
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        REACT_APP_ENVIRONMENT: production
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./frontend
        vercel-args: '--prod'
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        REACT_APP_ENVIRONMENT: production
    
    - name: Get deployment URL
      id: vercel-url
      run: |
        echo "VERCEL_URL=${{ steps.deploy.outputs.preview-url }}" >> $GITHUB_OUTPUT
    
    - name: Health check frontend
      run: |
        sleep 30
        for i in {1..5}; do
          if curl -f "${{ secrets.FRONTEND_URL }}"; then
            echo "✅ Frontend is live!"
            exit 0
          fi
          echo "Attempt $i failed, retrying in 15s..."
          sleep 15
        done
        echo "❌ Frontend health check failed"
        exit 1
    
    - name: Deployment success
      if: success()
      run: |
        echo "🎉 Frontend deployed successfully to Vercel!"
        echo "URL: ${{ secrets.FRONTEND_URL }}"